name = "HybridSolve"
uuid = "d40718ad-d2a0-494e-bdde-714dfcc15d11"
version = "0.1.0"
authors = ["Xuanzhao Gao <xgao@flatironinstitute.org> and contributors"]

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10"

[extras]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SHA", "Test"]
